services:
  mongo:
    image: mongo:7
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  cassandra:
    image: cassandra:4
    container_name: cassandra
    restart: always
    environment:
      - CASSANDRA_CLUSTER_NAME=bench_cluster
      - MAX_HEAP_SIZE=1G
      - HEAP_NEWSIZE=256M
    ports:
      - "9042:9042"

  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb
    restart: always
    ports:
      - "8000:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb"]
